#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AUDIT_DIR="${AUDIT_DIR:-$ROOT_DIR/control-plane/AUDITS}"
STAMP="$(date -u +"%Y-%m-%dT%H%M%SZ")"
OUTPUT_PATH="${1:-$AUDIT_DIR/${STAMP}-vps-audit-auto.md}"

mkdir -p "$AUDIT_DIR"

tmpdir="$(mktemp -d)"
cleanup() {
  rm -rf "$tmpdir"
}
trap cleanup EXIT

capture_optional_shell() {
  local name="$1"
  local command="$2"
  if command -v bash >/dev/null 2>&1; then
    bash -lc "$command" >"$tmpdir/$name" 2>&1 || true
  else
    : >"$tmpdir/$name"
  fi
}

if command -v rg >/dev/null 2>&1; then
  SERVICE_FILTER="rg -i 'chopsticks|nqita|caddy|redis|postgres|docker'"
else
  SERVICE_FILTER="grep -Ei 'chopsticks|nqita|caddy|redis|postgres|docker'"
fi

section() {
  local title="$1"
  local file="$2"
  printf '## %s\n\n' "$title" >>"$OUTPUT_PATH"
  if [[ -s "$file" ]]; then
    printf '```text\n' >>"$OUTPUT_PATH"
    cat "$file" >>"$OUTPUT_PATH"
    [[ "$(tail -c 1 "$file" 2>/dev/null || true)" == $'\n' ]] || printf '\n' >>"$OUTPUT_PATH"
    printf '```\n\n' >>"$OUTPUT_PATH"
  else
    printf '_No data collected._\n\n' >>"$OUTPUT_PATH"
  fi
}

capture_optional_shell services-enabled "systemctl list-unit-files --type=service --state=enabled --no-pager | $SERVICE_FILTER || true"
capture_optional_shell services-running "systemctl list-units --type=service --state=running --no-pager | $SERVICE_FILTER || true"
capture_optional_shell docker-ps "docker ps --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}' || true"
capture_optional_shell docker-volumes "docker volume ls || true"
capture_optional_shell compose-manifests "find /home/samhcharles/srv -maxdepth 4 \( -name 'docker-compose.yml' -o -name '*.service.example' -o -name 'Caddyfile' -o -name 'Caddyfile.*' \) | sort"
capture_optional_shell crontab "crontab -l || true"
capture_optional_shell timers "systemctl list-timers --all --no-pager | head -n 40 || true"
capture_optional_shell listening-ports "ss -ltn || true"
capture_optional_shell srv-logs "find /home/samhcharles/srv/logs -maxdepth 2 -mindepth 1 -printf '%y %p\\n' | sort || true"
capture_optional_shell srv-volumes "find /home/samhcharles/srv/volumes -maxdepth 2 -mindepth 1 -printf '%y %p\\n' | sort || true"
capture_optional_shell srv-agents "find /home/samhcharles/srv/agents -maxdepth 3 -printf '%y %p\\n' | sort || true"
capture_optional_shell srv-proxy "find /home/samhcharles/srv/proxy -maxdepth 3 -printf '%y %p\\n' | sort || true"
capture_optional_shell srv-backups "find /home/samhcharles/srv/backups -maxdepth 3 | sort || true"
capture_optional_shell chopsticks-repo-state "cd /home/samhcharles/srv/bots/chopsticks-lean && git remote -v && printf '\\n' && git status --short --branch && printf '\\n' && git log --oneline -n 3 || true"

cat >"$OUTPUT_PATH" <<EOF
# VPS Audit Snapshot ${STAMP}

Generated by \`scripts/capture-vps-audit.sh\`.

This snapshot is read-only and intended to capture runtime facts without editing the system.

EOF

section "Enabled Services Filter" "$tmpdir/services-enabled"
section "Running Services Filter" "$tmpdir/services-running"
section "Docker Containers" "$tmpdir/docker-ps"
section "Docker Volumes" "$tmpdir/docker-volumes"
section "Deploy Manifests" "$tmpdir/compose-manifests"
section "User Crontab" "$tmpdir/crontab"
section "System Timers" "$tmpdir/timers"
section "Listening TCP Ports" "$tmpdir/listening-ports"
section "Logs Tree" "$tmpdir/srv-logs"
section "Volumes Tree" "$tmpdir/srv-volumes"
section "Agents Tree" "$tmpdir/srv-agents"
section "Proxy Tree" "$tmpdir/srv-proxy"
section "Backups Tree" "$tmpdir/srv-backups"
section "Chopsticks Lean Repo State" "$tmpdir/chopsticks-repo-state"

printf 'Wrote %s\n' "$OUTPUT_PATH"